spring.application.name=Busca Apartamentos
server.port=8080
spring.thymeleaf.cache=false
apartments.demo.enabled=false
apartments.mercadolivre.enabled=true
apartments.mercadolivre.base-url=https://api.mercadolibre.com
apartments.mercadolivre.site-id=MLB
apartments.mercadolivre.rent-category-id=MLB1459
apartments.mercadolivre.sale-category-id=MLB1459
apartments.mercadolivre.access-token=
